// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "SimpleZipCore",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .library(name: "SimpleZipCore", targets: ["SimpleZipCore"])
    ],
    targets: [
        .target(
            name: "SimpleZipCore",
            path: "SimpleZip",
            exclude: [
                "App",
                "AppIcon.icns",
                "Assets.xcassets",
                "Features",
                "Tools",
                "de.lproj",
                "en.lproj",
                "es.lproj",
                "fr.lproj",
                "ja.lproj",
                "ko.lproj",
                "ru.lproj",
                "th.lproj",
                "zh-Hans.lproj",
                "zh-Hant.lproj"
            ],
            sources: [
                "Core/AI/AIArchiveInternalMap.swift",
                "Core/AI/AIBackgroundIndexRun.swift",
                "Core/AI/AIBudget.swift",
                "Core/AI/AICompactContextCodec.swift",
                "Core/AI/AIContext.swift",
                "Core/AI/AIContextPipeline.swift",
                "Core/AI/AIDataGap.swift",
                "Core/AI/AIDataLifecycle.swift",
                "Core/AI/AIDependencyEnvironment.swift",
                "Core/AI/AIDerivedDataStore.swift",
                "Core/AI/AIDiagnostics.swift",
                "Core/AI/AIDiffExplanation.swift",
                "Core/AI/AIEmptyStateReason.swift",
                "Core/AI/AIEngine.swift",
                "Core/AI/AIEnrichmentAction.swift",
                "Core/AI/AIFailureDegradation.swift",
                "Core/AI/AIFailurePlaybook.swift",
                "Core/AI/AIFileMemory.swift",
                "Core/AI/AIFilenameEncoding.swift",
                "Core/AI/AIFileSystemFact.swift",
                "Core/AI/AIFileMemoryIndex.swift",
                "Core/AI/AIForegroundLock.swift",
                "Core/AI/AIIndexMaintenance.swift",
                "Core/AI/AIIndexerScan.swift",
                "Core/AI/AIIntentRouter.swift",
                "Core/AI/AIInteractionSignal.swift",
                "Core/AI/AIInterventionGate.swift",
                "Core/AI/ContextualToolbarActionProvider.swift",
                "Core/AI/AIFeedback.swift",
                "Core/AI/AILens.swift",
                "Core/AI/AILocationContext.swift",
                "Core/AI/AINextActionCard.swift",
                "Core/AI/AIOperationAdvice.swift",
                "Core/AI/AIOperationOptionPatch.swift",
                "Core/AI/AIPendingCheck.swift",
                "Core/AI/AIPrefetch.swift",
                "Core/AI/AIPrereadSelection.swift",
                "Core/AI/AIPresetRecommendation.swift",
                "Core/AI/AIRanking.swift",
                "Core/AI/AIReleaseChecklist.swift",
                "Core/AI/AISchemaMigration.swift",
                "Core/AI/AISearchRewrite.swift",
                "Core/AI/AISecurityAttention.swift",
                "Core/AI/AISelectionQuery.swift",
                "Core/AI/AISemanticTag.swift",
                "Core/AI/AISettingsDoctor.swift",
                "Core/AI/AIStartupSuggestion.swift",
                "Core/AI/AISuggestionBus.swift",
                "Core/AI/AISystemWorkspaceFacts.swift",
                "Core/AI/AIThemeSuppression.swift",
                "Core/AI/AITaskPlan.swift",
                "Core/AI/AITimeSemantics.swift",
                "Core/AI/AIUserInterestEvent.swift",
                "Core/AI/AIURLCandidateExtractor.swift",
                "Core/AI/AIVersionRelation.swift",
                "Core/AI/AIVirtualFolderPlan.swift",
                "Core/AI/ActivityTaskAIIndex.swift",
                "Core/AI/AISensitiveRedactor.swift",
                "Core/AppPreferences.swift",
                "Core/ArchiveError.swift",
                "Core/ArchiveOperationFeedback.swift",
                "Core/ArchiveCreationService.swift",
                "Core/ArchiveDiff.swift",
                "Core/ArchiveListingCache.swift",
                "Core/ArchiveMemoryIndex.swift",
                "Core/ArchiveModels.swift",
                "Core/ArchivePasswordContextHint.swift",
                "Core/ArchiveEntryUpdate.swift",
                "Core/ArchiveWriteGate.swift",
                "Core/ChecksumFile.swift",
                "Core/CLIInvocation.swift",
                "Core/CLICompletions.swift",
                "Core/ArchiveOperationOptions.swift",
                "Core/ArchiveSafety.swift",
                "Core/ArchiveContentSearch.swift",
                "Core/ArchiveSalvage.swift",
                "Core/ArchiveSearch.swift",
                "Core/AI/AIWorkspaceQueryPlan.swift",
                "Core/AI/AIWorkspaceCandidate.swift",
                "Core/AI/AIWorkspaceEvidenceGapBuilder.swift",
                "Core/AI/AINodeFeedback.swift",
                "Core/AI/AIWorkspaceStructureEdits.swift",
                "Core/AI/AIWorkspaceSeedRecall.swift",
                "Core/AI/AIWorkspaceLearningStore.swift",
                "Core/AI/AIWorkspaceReviewPumpPolicy.swift",
                "Core/AI/AIWorkspaceDiscovery.swift",
                "Core/AI/AIWorkspaceModel.swift",
                "Core/AI/AIWorkspaceThemeEngine.swift",
                "Core/AI/AIWorkspaceDynamicTheme.swift",
                "Core/AI/ActivityAIWorkbench.swift",
                "Core/ArchiveCheckup.swift",
                "Core/ArchiveRiskScore.swift",
                "Core/ArchiveProfile.swift",
                "Core/ArchiveProperties.swift",
                "Core/ArchiveRoleClassifier.swift",
                "Core/ArchiveSpaceAnalysis.swift",
                "Core/SensitiveFileScan.swift",
                "Core/ArchiveNearDuplicates.swift",
                "Core/ArchiveTransferModels.swift",
                "Core/ArchiveConversion.swift",
                "Core/FormatCapabilityMatrix.swift",
                "Core/ArchiveService+Arguments.swift",
                "Core/ArchiveService+Parsing.swift",
                "Core/ArchiveService.swift",
                "Core/BackendProcessRunner.swift",
                "Core/PerfSignpost.swift",
                "Core/PathHealthCheck.swift",
                "Core/ReproducibilityReport.swift",
                "Core/CompressionEstimator.swift",
                "Core/BrowserGrouping.swift",
                "Core/BundleReleaseCheck.swift",
                "Core/CompressionPreset.swift",
                "Core/CompressionUsageStore.swift",
                "Core/ExtractionUsageStore.swift",
                "Core/Backends/ArchiveBackend.swift",
                "Core/Backends/DiskImageBackend.swift",
                "Core/Backends/GPGBackend.swift",
                "Core/Backends/GPGBackend+Discovery.swift",
                "Core/Backends/GPGBackend+Keyring.swift",
                "Core/Backends/GPGBackend+KeyManagement.swift",
                "Core/Backends/GPGBackend+KeyLifecycle.swift",
                "Core/Backends/GPGBackend+KeyCreation.swift",
                "Core/Backends/GPGBackend+CryptoOperations.swift",
                "Core/Backends/GPGBackend+Parsing.swift",
                "Core/Backends/GPGBackend+Keyserver.swift",
                "Core/Backends/GPGModels.swift",
                "Core/Backends/NativeZipBackend.swift",
                "Core/Backends/RarBackend.swift",
                "Core/Backends/SevenZipBackend.swift",
                "Core/Backends/XIPBackend.swift",
                "Core/FileBrowserOutline.swift",
                "Core/FileSplitCombine.swift",
                "Core/FinderFavoritesReader.swift",
                "Core/GPGFileKind.swift",
                "Core/HashModels.swift",
                "Core/L10n.swift",
                "Core/OperationDiagnosticsReporter.swift",
                "Core/PreferencesPayloadCodec.swift",
                "Core/PresetPasswordStore.swift",
                "Core/ReleaseDirectoryAudit.swift",
                "Core/ReleaseGate.swift",
                "Core/ReleaseInspectionReport.swift",
                "Core/ReleaseLedger.swift",
                "Core/ReleaseLedgerComparison.swift",
                "Core/ReleaseManifest.swift",
                "Core/ReleaseNotesDraft.swift",
                "Core/ReleaseWorkspacePreset.swift",
                "Core/ReleaseRunRecord.swift",
                "Core/ReportExport.swift",
                "Core/SecureScratchVolume.swift",
                "Core/SIZArchive.swift",
                "Core/SZSArchive.swift",
                "Core/TemporaryResourceManager.swift",
                "Core/UndoFileSnapshot.swift",
                "Core/UniqueFileName.swift",
                "Core/ZipArchiveComment.swift"
            ]
        ),
        .testTarget(
            name: "SimpleZipCoreTests",
            dependencies: ["SimpleZipCore"],
            path: "Tests/SimpleZipCoreTests",
            // Fixtures/ 下是预录的二进制压缩包 + 生成脚本 + README，
            // 通过 Bundle.module 给测试代码拿到 URL，避免依赖 swift test 当前工作目录。
            resources: [
                .copy("Fixtures")
            ]
        )
    ]
)
