// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "SimpleZipCore",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .library(name: "SimpleZipCore", targets: ["SimpleZipCore"])
    ],
    targets: [
        .target(
            name: "SimpleZipCore",
            path: "SimpleZip",
            exclude: [
                "App",
                "AppIcon.icns",
                "Assets.xcassets",
                "Features",
                "Tools",
                "de.lproj",
                "en.lproj",
                "es.lproj",
                "fr.lproj",
                "ja.lproj",
                "ko.lproj",
                "ru.lproj",
                "th.lproj",
                "zh-Hans.lproj",
                "zh-Hant.lproj"
            ],
            sources: [
                "Core/AIBudget.swift",
                "Core/AIContext.swift",
                "Core/AIDiagnostics.swift",
                "Core/AIFeedback.swift",
                "Core/AILocationContext.swift",
                "Core/ActivityTaskAIIndex.swift",
                "Core/AISensitiveRedactor.swift",
                "Core/AppPreferences.swift",
                "Core/ArchiveError.swift",
                "Core/ArchiveOperationFeedback.swift",
                "Core/ArchiveCreationService.swift",
                "Core/ArchiveDiff.swift",
                "Core/ArchiveListingCache.swift",
                "Core/ArchiveMemoryIndex.swift",
                "Core/ArchiveModels.swift",
                "Core/ArchiveEntryUpdate.swift",
                "Core/ArchiveWriteGate.swift",
                "Core/ChecksumFile.swift",
                "Core/CLIInvocation.swift",
                "Core/CLICompletions.swift",
                "Core/ArchiveOperationOptions.swift",
                "Core/ArchiveSafety.swift",
                "Core/ArchiveContentSearch.swift",
                "Core/ArchiveSalvage.swift",
                "Core/ArchiveSearch.swift",
                "Core/AIWorkspaceQueryPlan.swift",
                "Core/ArchiveCheckup.swift",
                "Core/ArchiveRiskScore.swift",
                "Core/ArchiveProfile.swift",
                "Core/ArchiveProperties.swift",
                "Core/ArchiveRoleClassifier.swift",
                "Core/ArchiveSpaceAnalysis.swift",
                "Core/SensitiveFileScan.swift",
                "Core/ArchiveNearDuplicates.swift",
                "Core/ArchiveTransferModels.swift",
                "Core/ArchiveConversion.swift",
                "Core/FormatCapabilityMatrix.swift",
                "Core/ArchiveService+Arguments.swift",
                "Core/ArchiveService+Parsing.swift",
                "Core/ArchiveService.swift",
                "Core/BackendProcessRunner.swift",
                "Core/PerfSignpost.swift",
                "Core/PathHealthCheck.swift",
                "Core/ReproducibilityReport.swift",
                "Core/CompressionEstimator.swift",
                "Core/BrowserGrouping.swift",
                "Core/BundleReleaseCheck.swift",
                "Core/CompressionPreset.swift",
                "Core/CompressionUsageStore.swift",
                "Core/ExtractionUsageStore.swift",
                "Core/Backends/ArchiveBackend.swift",
                "Core/Backends/DiskImageBackend.swift",
                "Core/Backends/GPGBackend.swift",
                "Core/Backends/GPGBackend+Discovery.swift",
                "Core/Backends/GPGBackend+Keyring.swift",
                "Core/Backends/GPGBackend+KeyManagement.swift",
                "Core/Backends/GPGBackend+KeyLifecycle.swift",
                "Core/Backends/GPGBackend+KeyCreation.swift",
                "Core/Backends/GPGBackend+CryptoOperations.swift",
                "Core/Backends/GPGBackend+Parsing.swift",
                "Core/Backends/GPGBackend+Keyserver.swift",
                "Core/Backends/GPGModels.swift",
                "Core/Backends/NativeZipBackend.swift",
                "Core/Backends/RarBackend.swift",
                "Core/Backends/SevenZipBackend.swift",
                "Core/Backends/XIPBackend.swift",
                "Core/FileBrowserOutline.swift",
                "Core/FileSplitCombine.swift",
                "Core/FinderFavoritesReader.swift",
                "Core/GPGFileKind.swift",
                "Core/HashModels.swift",
                "Core/L10n.swift",
                "Core/OperationDiagnosticsReporter.swift",
                "Core/PreferencesPayloadCodec.swift",
                "Core/PresetPasswordStore.swift",
                "Core/ReleaseDirectoryAudit.swift",
                "Core/ReleaseGate.swift",
                "Core/ReleaseInspectionReport.swift",
                "Core/ReleaseLedger.swift",
                "Core/ReleaseLedgerComparison.swift",
                "Core/ReleaseManifest.swift",
                "Core/ReleaseNotesDraft.swift",
                "Core/ReleaseWorkspacePreset.swift",
                "Core/ReleaseRunRecord.swift",
                "Core/ReportExport.swift",
                "Core/SecureScratchVolume.swift",
                "Core/SIZArchive.swift",
                "Core/SZSArchive.swift",
                "Core/TemporaryResourceManager.swift",
                "Core/UndoFileSnapshot.swift",
                "Core/UniqueFileName.swift",
                "Core/ZipArchiveComment.swift"
            ]
        ),
        .testTarget(
            name: "SimpleZipCoreTests",
            dependencies: ["SimpleZipCore"],
            path: "Tests/SimpleZipCoreTests",
            // Fixtures/ 下是预录的二进制压缩包 + 生成脚本 + README，
            // 通过 Bundle.module 给测试代码拿到 URL，避免依赖 swift test 当前工作目录。
            resources: [
                .copy("Fixtures")
            ]
        )
    ]
)
