import Foundation
import Testing
@testable import SimpleZipCore

/// 0.4.3 #11:校验文件解析 / 生成。生成必须 GNU 兼容(`sha256sum -c` 可验),
/// 解析要容下 GNU / BSD / SFV / 单摘要 sidecar 四种野生格式。
struct ChecksumFileTests {

    @Test func recognizesChecksumFileNames() {
        #expect(ChecksumFile.isChecksumFileName("SHA256SUMS"))
        #expect(ChecksumFile.isChecksumFileName("sha256sums"))
        #expect(ChecksumFile.isChecksumFileName("checksums.txt"))
        #expect(ChecksumFile.isChecksumFileName("app.dmg.sha256"))
        #expect(ChecksumFile.isChecksumFileName("backup.md5"))
        #expect(ChecksumFile.isChecksumFileName("episode.sfv"))
        #expect(!ChecksumFile.isChecksumFileName("notes.txt"))
        #expect(!ChecksumFile.isChecksumFileName("archive.zip"))
    }

    @Test func parsesGNUFormat() {
        let sha = String(repeating: "ab", count: 32)
        let text = """
        # comment line
        \(sha)  release.zip
        \(sha) *binary mode.dmg
        """
        let entries = ChecksumFile.parse(text, fileName: "SHA256SUMS")
        #expect(entries.count == 2)
        #expect(entries[0] == ChecksumFileEntry(name: "release.zip", digestHex: sha, algorithm: .sha256))
        #expect(entries[1].name == "binary mode.dmg")
    }

    @Test func parsesBSDFormat() {
        let md5 = String(repeating: "1a", count: 16)
        let entries = ChecksumFile.parse("MD5 (my file.zip) = \(md5)", fileName: "checksums.txt")
        #expect(entries == [ChecksumFileEntry(name: "my file.zip", digestHex: md5, algorithm: .md5)])
    }

    @Test func parsesSFVFormat() {
        let text = """
        ; generated by some tool
        episode 01.mkv ABCD1234
        """
        let entries = ChecksumFile.parse(text, fileName: "set.sfv")
        #expect(entries == [ChecksumFileEntry(name: "episode 01.mkv", digestHex: "abcd1234", algorithm: .crc32)])
    }

    @Test func parsesSingleDigestSidecar() {
        let sha = String(repeating: "0f", count: 32)
        let entries = ChecksumFile.parse("\(sha)\n", fileName: "app.dmg.sha256")
        #expect(entries == [ChecksumFileEntry(name: "app.dmg", digestHex: sha, algorithm: .sha256)])
    }

    @Test func skipsGarbageLines() {
        let entries = ChecksumFile.parse("not a checksum line\nzzzz  name.txt\n", fileName: "SHA256SUMS")
        #expect(entries.isEmpty)
    }

    @Test func generatesGNUCompatibleOutput() {
        let sha = String(repeating: "cd", count: 32)
        let text = ChecksumFile.generateSHA256SUMS([(name: "a.zip", digestHex: sha.uppercased())])
        #expect(text == "\(sha)  a.zip\n")
        // round-trip:自己生成的自己必须能解析回来。
        let parsed = ChecksumFile.parse(text, fileName: "SHA256SUMS")
        #expect(parsed == [ChecksumFileEntry(name: "a.zip", digestHex: sha, algorithm: .sha256)])
    }

    @Test func infersAlgorithmsByLength() {
        #expect(ChecksumAlgorithm.inferred(fromHexLength: 8) == .crc32)
        #expect(ChecksumAlgorithm.inferred(fromHexLength: 32) == .md5)
        #expect(ChecksumAlgorithm.inferred(fromHexLength: 40) == .sha1)
        #expect(ChecksumAlgorithm.inferred(fromHexLength: 64) == .sha256)
        #expect(ChecksumAlgorithm.inferred(fromHexLength: 128) == .sha512)
        #expect(ChecksumAlgorithm.inferred(fromHexLength: 10) == nil)
    }
}
